spring:
  zipkin:
    enabled: false
data-platform:
  kafka:
    bootstrap: localhost:9092

server:
  port: 8001

management:
  endpoint:
    health:
      probes:
        enabled: true

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081