spring:
  application:
    name: user-settings-service-api
  mvc:
    throw-exception-if-no-handler-found: true
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id, x-access-token
      correlation-fields: x-request-id
  web:
    resources:
      add-mappings: false
  redis:
    password: ${REDIS_PASSWORD}
    sentinel:
      master: mymaster
      nodes:
        - ${REDIS_NODE}

springdoc:
  swagger-ui:
    path: /openapi
    csrf:
      enabled: true

openapi:
  request:
    headers:
      - X-Access-Token
  response:
    codes:
      get-by-id: 200, 400, 401, 500
      post: 200, 400, 401, 422, 500

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck
        readiness:
          include: readinessState, db, kafka, redis
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

probes:
  liveness:
    failureThreshold: 10

platform:
  security:
    enabled: true
    whitelist:
      - /openapi
      - /v3/api-docs/**
      - /swagger-ui/**
      - /actuator/**

logbook:
  exclude:
    - /openapi
    - /v3/api-docs/**
    - /swagger-ui/**
    - /actuator/**
