spring:
  zipkin:
    enabled: false
  autoconfigure:
    exclude: com.epam.digital.data.platform.starter.database.DatabaseAutoConfiguration
  sql:
    init:
      mode: always

data-platform:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
      
audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false
